#!/bin/bash
#
# We cat the /etc/passwd. Then i use awk and -F (sets field separator) ':' 
# we print the user $1 and the UID $3 path $6
# Thanks to separator we get it done simple way.
#
# and last we use column it will columnate list and
# -t table so we get it to look nicer
cat /etc/passwd | awk -F ':' '{print $1 " ", $3 " ", $6}' | column -t